version: "3.7"

services:
  # 1. Elasticsearch - 数据库
  elasticsearch:
    image: elasticsearch:7.17.21 
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node # 单节点模式
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 限制内存，防止 Mac 变卡
      - xpack.security.enabled=false # 关闭安全验证，方便开发
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk-net

  # 2. Logstash - 搬运与清洗
  logstash:
    image: logstash:7.17.21
    container_name: logstash
    volumes:
      # 挂载配置文件
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # [核心步骤] 将 Mac 本地的 logs 目录挂载到容器内
      - ./logs:/usr/share/logstash/external_logs
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  # 3. Kibana - 可视化界面
  kibana:
    image: kibana:7.17.21
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-net

volumes:
  es_data:

networks:
  elk-net:
    driver: bridge
